dist: trusty

language: node_js
node_js:
  - "6"
  - "8"

env:
  global:
    secure: I9sReagJiE7B0154AnU3t8WcdPtmZm86vMp+6umKegvzYr46jbypPAmlWW50A09fw4AmTaGOtwpYtvglf0JikkR6saXY0rRquDnO70DRmbdrO2o2WMjjCzkYID58SkGvqsqVJ4HXcu0HdJp6o5L7v7JMdzji6abYKxtsnw2ouk0=

  matrix:
    - TEST_SCRIPT=build
    - TEST_SCRIPT=cover
    - TEST_SCRIPT=fix

matrix:
  exclude:
    - node_js: "6"
      env: TEST_SCRIPT=cover
    - node_js: "6"
      env: TEST_SCRIPT=fix
  include:
    - node_js: "6"
      addons:
        chrome: stable
      env: TEST_SCRIPT=test
    - node_js: "8"
      addons:
        chrome: stable
      env: TEST_SCRIPT=test

script: ./scripts/ci.sh $TEST_SCRIPT

cache: yarn

notifications:
  email: never
  slack:
    rooms:
      - vega-js:eJe5JNgxfucTVcTMbeplKX3v
    on_success: never
    on_failure: always
